language: android

jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
- ./gradlew :fluxjava:check
- ./gradlew :fluxjava-rx:check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false