language: android

jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

# Using cache to speed up
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Uncomment the line below to speed up
# install: echo "skip 'gradle assemble' step"

script:
- ./gradlew :fluxjava:build
- ./gradlew :fluxjava-rx:build
- ./gradlew :fluxjava-rx2:build

after_success:
  # Code coverage
  - bash <(curl -s https://codecov.io/bash)
  # Make pacakge for Github releases
  - ./gradlew :binaryZip

# Push to Github releases
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "build/binary.zip"
  skip_cleanup: true
  on:
    tags: true # Only push commit with tag

notifications:
  email: false